version: '3'

services:
  web:
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/web/src
      - web-static:/web/src/static
    env_file : env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn notes.wsgi:application -w 2 -b :8000


  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web
  

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/


  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata: